modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="tidebound"
version="0.9.0-alpha"
displayName="Tidebound Core"
authors="Tidebound"
description='''
Socle de Tidebound : progression maritime, prises persistantes, navire personnel et interfaces de port.
'''

[[dependencies.tidebound]]
modId="neoforge"
type="required"
versionRange="[21.1.249,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.tidebound]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[features.tidebound]
javaVersion="[21,)"
